# Site settings
title: HCNOH's blog
description: HCNOH's blog
baseurl: "blog-prev/" # the subpath of your site, e.g. /blog
url: "https://hcnoh.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: HCNOH
user_description: Deep Learning Researcher at TmaxData
user_title: Hyungcheol's Blog
email: rhc0624@gmail.com
#twitter_username: lorem_ipsum
github_username:  hcnoh
gplus_username:  ArtZizou
disqus_username: hcnoh

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
